/**
 * Regenerates every mark the site serves, from the repo-root `design/`.
 *
 * `design/bastion-icon.svg` is itself generated — `make icon` builds it from
 * `design/bastion-mark.svg`, the same geometry it compiles into the app's Icon
 * Composer bundle. So the chain is one mark end to end:
 *
 *   design/bastion-mark.svg --make icon--> design/bastion-icon.svg
 *                                            --pnpm icons--> public/*
 *
 * Nothing here transcribes a coordinate, and that is the whole point. Cupertino
 * hand-copied these files out of a gitignored design directory once and they
 * drifted: the site served an earlier direction of the mark than the app
 * shipped. Run `pnpm icons` after `make icon` rather than moving files yourself.
 */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import sharp from "sharp";

import { composeCard } from "../../../scripts/lib/lockup.mjs";
import { SOCIAL_CARD } from "../src/config.ts";

const here = dirname(fileURLToPath(import.meta.url));
const pub = join(here, "..", "public");
const design = join(here, "..", "..", "..", "design");

/** Loud on a missing source: a silent skip here ships a stale mark. */
const source = async (name) => {
  try {
    return await readFile(join(design, name), "utf8");
  } catch {
    throw new Error(
      `design/${name} is missing. It is generated by \`make icon\` at the repo root — run that first.`,
    );
  }
};

/**
 * Throws rather than passing the artwork through unchanged, so a change to what
 * `make icon` emits surfaces here instead of silently producing a wrong icon.
 */
const replaceOnce = (text, find, replacement, what) => {
  if (!text.includes(find)) throw new Error(`${what}: expected to find ${find}`);
  return text.replace(find, replacement);
};

const png = async (svg, out, size) => {
  const buf = await sharp(Buffer.from(svg), { density: 400 }).resize(size, size).png().toBuffer();
  await writeFile(join(pub, out), buf);
  console.log(`  ${out}  ${size}×${size}`);
};

console.log("icons →");

const icon = await source("bastion-icon.svg");
const menubar = await source("bastion-menubar.svg");
const menubarActive = await source("bastion-menubar-active.svg");

// Served as-is: /favicon.svg is linked by every page, /app-icon.svg is what
// every <Logo> on the site renders, and the two menu bar glyphs are the mark in
// the hero's menu bar mock — idle, and with the curtain wall the app draws while
// a server is running. All four have to exist in the built site.
await writeFile(join(pub, "app-icon.svg"), icon);
await writeFile(join(pub, "favicon.svg"), icon);
await writeFile(join(pub, "menubar-glyph.svg"), menubar);
await writeFile(join(pub, "menubar-glyph-active.svg"), menubarActive);
console.log("  app-icon.svg, favicon.svg, menubar-glyph[-active].svg  copied from design/");

await png(icon, "favicon-32.png", 32);

// iOS applies its own mask to the touch icon, so the plate is squared first —
// otherwise the corner radius is applied twice and the artwork reads pinched.
// `make icon` adds this clip-path for the web; here it comes back off.
await png(
  replaceOnce(icon, ' clip-path="url(#c)"', "", "apple-touch-icon"),
  "apple-touch-icon.png",
  180,
);

// The Stripe product image, shown beside the line item on the hosted checkout.
// Stripe stores the URL and fetches it rather than taking an upload — the live
// product's `images` points at this file — so the mark on the checkout page
// follows a site deploy, and the payment link behind /buy is never touched.
// Renaming or deleting this file breaks a page nothing in this repo builds.
// 512 is generous for a thumbnail, and the plate keeps its own corner radius:
// Stripe rounds the container far less than the squircle does, so squaring it
// the way the touch icon does would show as a crop.
await png(icon, "product-image.png", 512);

// The OG card is what a link to the site looks like on X, Slack and iMessage.
// It is the lockup reversed out of the page's own background, over two lines the
// site owns — composed by scripts/lib/lockup.mjs, which is also what writes the
// README banner, so the artwork cannot fork between the two.
//
// The words and the ground come from src/config.ts rather than from here: they
// are claims about the product, and this file has no business being the
// authority on one.
const card = composeCard(icon, JSON.parse(await source("colors.json")), SOCIAL_CARD);
await writeFile(
  join(pub, "og-image.png"),
  await sharp(Buffer.from(card), { density: 200 }).png({ palette: true }).toBuffer(),
);
console.log(`  og-image.png  ${SOCIAL_CARD.width}×${SOCIAL_CARD.height}`);
